version: "3.3"

services:

  postgres14db:
    build: db-configs/postgres
    ports:
      - 5432:5432
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: nimda
      PGDATA: /var/lib/postgresql/pgdata

  mysql8db:
    build: db-configs/mysql
    command: "--default-authentication-plugin=mysql_native_password --datadir=/var/lib/mysql-no-volume"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: nimda

  mariadb10db:
    build: db-configs/mariadb
    command: --datadir=/var/lib/mysql-no-volume
    ports:
      - 3010:3306
    environment:
      MYSQL_ROOT_PASSWORD: nimda

  mssql2019:
    build: db-configs/mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: secure1234PASSWORD!

  oracle19c:
    build: db-configs/oracle
    ports:
      - 1521:1521
      - 5529:5500
    volumes:
      - ./db-configs/oracle/dbca.rsp.tmpl:/opt/oracle/dbca.rsp.tmpl
    environment:
      ORACLE_PWD: nimda
      ORACLE_SID: ORASID
      ORACLE_PDB: ORAPDB
